# Generated by Django 3.2.13 on 2022-04-23 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesspoint_name', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=70)),
                ('event_address', models.CharField(max_length=70)),
                ('organiser_name', models.CharField(max_length=70)),
                ('organiser_email', models.CharField(max_length=70)),
                ('event_created_at', models.DateTimeField(auto_now_add=True)),
                ('event_updated_at', models.DateTimeField(auto_now=True)),
                ('event_active', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_booked', models.BooleanField(default=False)),
                ('accesspoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.accesspoint')),
                ('event_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eventdate')),
            ],
        ),
        migrations.CreateModel(
            name='TimeLapse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_lapse', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SlotAccessPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesspoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.accesspoint')),
                ('event_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eventslot')),
            ],
        ),
        migrations.AddField(
            model_name='eventslot',
            name='time_lapse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.timelapse'),
        ),
    ]
